//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aeronaves
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Serie { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> Capacidad { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Arolinea { get; set; }
        public string Piloto { get; set; }
    
        public virtual Aerolinea Aerolinea { get; set; }
        public virtual Pilotos Pilotos { get; set; }
    }
}
