//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alquiler
    {
        public int Id { get; set; }
        public string DondeViaja { get; set; }
        public string FechaLLegada { get; set; }
        public string FechaSalida { get; set; }
        public Nullable<int> CantidadPasajetos { get; set; }
    }
}
